openapi: 3.1.0
info:
  version: 1.0.0
  title: Node.js HW API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    Node.js kursu için örnek API dokümantasyonu.
tags:
  - name: Auth
    description: Kimlik doğrulama işlemleri
  - name: Contacts
    description: Kişi yönetimi
servers:
  - url: http://localhost:3000
  - url: https://<yayınlanmış-site-linki>
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml#get
    post:
      $ref: ../swagger/paths/contacts/post.yaml#post
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml#get
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml#patch
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml#delete
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
